// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMRH09oYA-CMS7d0XFe4izZAuji3XS9lk',
    appId: '1:607005253117:web:2ffa08820a11e048198d94',
    messagingSenderId: '607005253117',
    projectId: 'knowledgeoftheday-519d0',
    authDomain: 'knowledgeoftheday-519d0.firebaseapp.com',
    storageBucket: 'knowledgeoftheday-519d0.appspot.com',
    measurementId: 'G-BEYZTP3XBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9AiNQS0wYsVXyJFayOVqLgHfoYOagqWA',
    appId: '1:607005253117:android:e32c5bf827a82957198d94',
    messagingSenderId: '607005253117',
    projectId: 'knowledgeoftheday-519d0',
    storageBucket: 'knowledgeoftheday-519d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UoQFjm8LoBeQIQgIMi4HxGFbD7oVL2Y',
    appId: '1:607005253117:ios:56ff6ec0583851b3198d94',
    messagingSenderId: '607005253117',
    projectId: 'knowledgeoftheday-519d0',
    storageBucket: 'knowledgeoftheday-519d0.appspot.com',
    iosClientId: '607005253117-4gc2j0hj8cfvu1fp13j5ljvidoh0n5kj.apps.googleusercontent.com',
    iosBundleId: 'dev.curth.kotd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UoQFjm8LoBeQIQgIMi4HxGFbD7oVL2Y',
    appId: '1:607005253117:ios:56ff6ec0583851b3198d94',
    messagingSenderId: '607005253117',
    projectId: 'knowledgeoftheday-519d0',
    storageBucket: 'knowledgeoftheday-519d0.appspot.com',
    iosClientId: '607005253117-4gc2j0hj8cfvu1fp13j5ljvidoh0n5kj.apps.googleusercontent.com',
    iosBundleId: 'dev.curth.kotd',
  );
}
